version: "3.9"

services:
  snowflake-proxy:
    image: thetorproject/snowflake-proxy:latest
    entrypoint: /opt/start-scripts/nat-client-entrypoint.sh
    # TODO: update once broker and server are up
    command: [ "proxy" , "--broker" , "http://$BROKER_WAN_ADDR:$BROKER_PORT/" , "--relay" , "wss://snowflake.torproject.net/" ]
    environment:
      NAT_ROUTER_LAN_ADDR: "$PROXY_NAT_ROUTER_LAN_ADDR"
    volumes:
        - ./start-scripts:/opt/start-scripts
    networks:
      proxy-lan:
        ipv4_address: "$PROXY_LAN_ADDR"
    cap_add:
      - ALL # TODO: check which for ip route

  proxy-nat-router:
    build: ./nat-router
    networks:
      proxy-lan:
        ipv4_address: "$PROXY_NAT_ROUTER_LAN_ADDR"
      wan:
        ipv4_address: "$PROXY_NAT_ROUTER_WAN_ADDR"
    volumes:
        - ./start-scripts:/opt/start-scripts
    command: /opt/start-scripts/nat-router-start.sh
    env_file:
     - .env
    environment:
      LAN_ADDR: "$PROXY_NAT_ROUTER_LAN_ADDR"
      WAN_ADDR: "$PROXY_NAT_ROUTER_WAN_ADDR"
    cap_add:
      - ALL # TODO: check which for iptables

  snowflake-client:
    build: ./snowflake-client
    entrypoint: /opt/start-scripts/snowflake-client-entrypoint.sh
    command: tor -f /opt/torrc-client
    env_file:
     - .env
    environment:
      NAT_ROUTER_LAN_ADDR: "$CLIENT_NAT_ROUTER_LAN_ADDR"
      TORRC_PATH: /opt/torrc-client
    volumes:
        - ./start-scripts:/opt/start-scripts
    networks:
      client-lan:
        ipv4_address: "$CLIENT_LAN_ADDR"
    cap_add:
      - ALL # TODO: check which for ip route

  client-nat-router:
    build: ./nat-router
    networks:
      client-lan:
        ipv4_address: "$CLIENT_NAT_ROUTER_LAN_ADDR"
      wan:
        ipv4_address: "$CLIENT_NAT_ROUTER_WAN_ADDR"
    volumes:
        - ./start-scripts:/opt/start-scripts
    command: /opt/start-scripts/nat-router-start.sh
    env_file:
     - .env
    environment:
      LAN_ADDR: "$CLIENT_NAT_ROUTER_LAN_ADDR"
      WAN_ADDR: "$CLIENT_NAT_ROUTER_WAN_ADDR"
    cap_add:
      - ALL # TODO: check which for iptables

  snowflake-broker:
    build: ./broker
    # TODO: need cmd?
    command: broker -addr ":$BROKER_PORT" -disable-tls -unsafe-logging
    networks:
      wan:
        ipv4_address: "$BROKER_WAN_ADDR"

networks:
  proxy-lan:
    ipam:
      config:
        - subnet: "$PROXY_LAN_SUBNET/$PROXY_LAN_SUFFIX"
          ip_range: "$PROXY_LAN_SUBNET/$PROXY_LAN_SUFFIX"
          gateway: "$PROXY_LAN_HOST_GATEWAY"

  client-lan:
    ipam:
      config:
        - subnet: "$CLIENT_LAN_SUBNET/$CLIENT_LAN_SUFFIX"
          ip_range: "$CLIENT_LAN_SUBNET/$CLIENT_LAN_SUFFIX"
          gateway: "$CLIENT_LAN_HOST_GATEWAY"

  wan:
    ipam:
      config:
        - subnet: "$WAN_SUBNET/$WAN_SUFFIX"
          ip_range: "$WAN_SUBNET/$WAN_SUFFIX"
          gateway: "$WAN_HOST_GATEWAY"

  # snowbox:
  #   user: root
  #   build:
  #     context: ./snowbox
  #     args:
  #       USER_ID: $USER_ID
  #       GROUP_ID: $GROUP_ID
  #   networks:
  #     lan:
  #       ipv4_address: "$SNOWBOX_LAN_ADDR"
  #   volumes:
  #       - "$SNOWFLAKE_WEBEXT_PATH":/go/src/snowflake-webext
  #       - "$SNOWFLAKE_SRC_PATH":/go/src/snowflake
  #       - ./start-scripts:/opt/start-scripts
  #   cap_add:
  #     - ALL # TODO: check which for ip route
  #   command: /opt/start-scripts/snowbox-start.sh
  #   env_file:
  #    - .env
